const TEAM = [
  { name: "Helen Achterberg", role: "Co-founder & CEO", team: "Leadership", leader: true, img: "helen-achterberg", location: "London", joined: "2016",
    bio: "Helen co-founded Northwind after a decade in product at large insurers. She sets direction, hires the leaders and still answers support emails on Fridays.", fun: "Restores old sailing boats.",
    quote: "Build the thing you'd want to use, then make it simpler." },
  { name: "Daniel Mensah", role: "Co-founder & CTO", team: "Leadership", leader: true, img: "daniel-mensah", location: "London", joined: "2016",
    bio: "Daniel wrote the first version of the platform in a shared flat. Today he leads architecture, security and the engineering org.", fun: "Keeps bees on the office roof.",
    quote: "Boring technology, exciting outcomes." },
  { name: "Lena Park", role: "Chief Product Officer", team: "Leadership", leader: true, img: "lena-park", location: "Bristol", joined: "2020",
    bio: "Lena joined from a consumer fintech to lead product, design and data. She owns the roadmap and our customer research practice.", fun: "Has visited 40 countries by train.",
    quote: "Every decision starts with a real customer story." },
  { name: "Maya Okafor", role: "Head of Engineering", team: "Engineering", img: "maya-okafor", location: "London", joined: "2019",
    bio: "Maya keeps the platform fast and the on-call rota calm. Before Northwind she built payment systems for a fintech start-up.", fun: "Has run every London Marathon since 2016." },
  { name: "Tom Lindqvist", role: "Senior Product Designer", team: "Design", img: "tom-lindqvist", location: "Stockholm", joined: "2021",
    bio: "Tom turns messy problems into clear flows. He leads our design system and runs the weekly crit.", fun: "Bakes a new kind of bread every Sunday." },
  { name: "Priya Raman", role: "Product Manager", team: "Product", img: "priya-raman", location: "Manchester", joined: "2020",
    bio: "Priya owns the onboarding journey and talks to at least three customers every week.", fun: "Plays tabla in a jazz-fusion band." },
  { name: "Kenji Watanabe", role: "Staff Engineer", team: "Engineering", img: "kenji-watanabe", location: "Remote", joined: "2018",
    bio: "Kenji designs the systems behind our quoting engine and mentors the backend guild.", fun: "Collects vintage mechanical keyboards." },
  { name: "Amara Diallo", role: "Head of Operations", team: "Operations", img: "amara-diallo", location: "London", joined: "2017",
    bio: "Amara makes sure every customer query gets a fast, human answer, and that the team behind them is supported.", fun: "Speaks five languages, learning a sixth." },
  { name: "Oliver Grant", role: "iOS Engineer", team: "Engineering", img: "oliver-grant", location: "Edinburgh", joined: "2022",
    bio: "Oliver crafts the details in our iOS app, from haptics to accessibility.", fun: "Wild-swims in the North Sea all year." },
  { name: "Sofia Moreno", role: "Content Designer", team: "Design", img: "sofia-moreno", location: "Barcelona", joined: "2023",
    bio: "Sofia writes the words you read in the app and keeps our tone warm and plain.", fun: "Has a cat called Semicolon." },
  { name: "Ravi Shah", role: "Data Analyst", team: "Product", img: "ravi-shah", location: "Birmingham", joined: "2021",
    bio: "Ravi finds the story in the numbers and builds the dashboards everyone checks on Monday.", fun: "Ranked top 500 in the UK at chess." },
  { name: "Chloé Dubois", role: "Head of Marketing", team: "Marketing", img: "chloe-dubois", location: "Paris", joined: "2021",
    bio: "Chloé leads brand and growth. She launched our first TV campaign and keeps every channel sounding like us.", fun: "Once won a regional croissant-baking contest." },
  { name: "Marcus Reid", role: "Growth Marketing Manager", team: "Marketing", img: "marcus-reid", location: "Leeds", joined: "2022",
    bio: "Marcus runs paid acquisition and experiments, and turns test results into next week's plan.", fun: "Plays bass in a ska covers band." },
  { name: "Aisha Khan", role: "Social & Community Lead", team: "Marketing", img: "aisha-khan", location: "London", joined: "2023",
    bio: "Aisha looks after our social channels and community, and is usually the first to spot what customers are talking about.", fun: "Has a houseplant collection of over 60 plants." },
];
